Repository nntile/nntile, pull requests merged in 2024-07, with the labels that each got.

#94 Adjust linting and testing CI workflows
  .github/scripts/run-dirty-tests.sh
  .github/workflows/check-pull-request.yml
  .github/workflows/on-push.yml
  .pre-commit-config.yaml
  README.md
  pyproject.toml
  wrappers/python/nntile/torch_models/__init__.py
  wrappers/python/tests/layer/huggingface_activations.py
  wrappers/python/tests/layer/test_attention.py
  wrappers/python/tests/model/test_gpt2.py
Labels: enhancement, ci

#98 Add workflow for nightly linting and testing
  .github/workflows/on-schedule.yml
Labels: enhancement, ci

#108 Add typing stubs for a native extension
  include/nntile/kernel/normalize/cpu.hh
  include/nntile/kernel/normalize/cuda.hh
  include/nntile/tensor/normalize.hh
  include/nntile/tile/normalize.hh
  src/kernel/normalize/cpu.cc
  src/kernel/normalize/cuda.cu
  src/tensor/normalize.cc
  src/tile/normalize.cc
  wrappers/python/nntile/nntile_core.cc
  wrappers/python/nntile/nntile_core/__init__.pyi
  wrappers/python/nntile/nntile_core/starpu.pyi
  wrappers/python/nntile/nntile_core/tensor/__init__.pyi
  wrappers/python/nntile/nntile_core/tensor/distributions.pyi
  wrappers/python/nntile/nntile_core/tile.pyi
Labels: enhancement

#109 Configure regular typing checks
  .github/workflows/on-push.yml
  .github/workflows/on-schedule.yml
  README.md
  pyproject.toml
  wrappers/python/nntile/functions.py
  wrappers/python/nntile/types.py
Labels: enhancement, ci

#106 Incorporate Rotary positional embedding into `LlamaAttention`
  include/CMakeLists.txt
  include/nntile/kernel.hh
  include/nntile/kernel/rope.hh
  include/nntile/kernel/rope/cpu.hh
  include/nntile/kernel/rope/cuda.hh
  include/nntile/kernel/rope_backward.hh
  include/nntile/kernel/rope_backward/cpu.hh
  include/nntile/kernel/rope_backward/cuda.hh
  include/nntile/starpu.hh
  include/nntile/starpu/rope.hh
  include/nntile/starpu/rope_backward.hh
  include/nntile/tensor.hh
  include/nntile/tensor/rope.hh
  include/nntile/tensor/rope_backward.hh
  include/nntile/tile.hh
  include/nntile/tile/rope.hh
  src/CMakeLists.txt
  src/kernel/rope/cpu.cc
  src/kernel/rope/cuda.cu
  src/kernel/rope_backward/cpu.cc
  src/kernel/rope_backward/cuda.cu
  src/starpu/rope.cc
  src/starpu/rope_backward.cc
  src/tensor/rope.cc
  src/tensor/rope_backward.cc
  src/tile/rope.cc
  tests/kernel/CMakeLists.txt
  tests/kernel/rope.cc
  tests/kernel/rope_backward.cc
  wrappers/python/nntile/functions.py
  wrappers/python/nntile/layer/llama_attention.py
  wrappers/python/nntile/nntile_core.cc
  wrappers/python/nntile/types.py
  wrappers/python/tests/conftest.py
  wrappers/python/tests/layer/test_llama_attention.py
Labels: enhancement, api

#110 Maintain typing compatibility with `python_version<3.12`
  pyproject.toml
  wrappers/python/nntile/nntile_core/tensor/__init__.pyi
  wrappers/python/nntile/nntile_core/tile.pyi
  wrappers/python/nntile/types.py
Labels: bug

#120 Revise LLaMA ingredients testing
  wrappers/python/nntile/model/llama.py
  wrappers/python/nntile/model/llama_config.py
  wrappers/python/nntile/model/llama_mlp.py
  wrappers/python/tests/layer/test_llama_attention.py
  wrappers/python/tests/model/test_llama.py
  wrappers/python/tests/model/test_llama_decoder.py
  wrappers/python/tests/model/test_llama_mlp.py
Labels: enhancement
